// makeswf -v 7 -s 200x150 -r 1 -o getvariable-length.swf getvariable-length.as

trace ("Test maximum length of variables in GetVariable lookups");

x = createEmptyMovieClip ("ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGH", 1);
trace (x);
x.yo = 127;
trace (ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGH.yo);
asm {
  push "ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGH:yo"
  getvariable
  trace
};

x = createEmptyMovieClip ("ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFG", 1);
x.H = { yo: 42 };
asm {
  push "ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGHI1ABCDEFGH:yo"
  getvariable
  trace
};

loadMovie ("FSCommand:quit", "");
